import { CourseTopic } from '@prisma/client';

const courseTopic: CourseTopic[] = [
  {
    id: 'CT_0001',
    nameEng: 'Front End career orientation, UI - UX platform',
    nameVn: 'Định hướng nghề Front End, UI - UX nền tảng',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0002',
    nameEng:
      'HTML, CSS, HTML5, CSS3, Layout, Flexbox across a variety of foundational to advanced projects',
    nameVn:
      'HTML, CSS, HTML5, CSS3, Layout, Flexbox qua nhiều dự án nền tảng đến chuyên sâu',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0003',
    nameEng: 'Bootstrap and Responsive design in action',
    nameVn: 'Bootstrap và Responsive design trong thực tế',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0004',
    nameEng: 'Practical SASS/SCSS background & depth through the project',
    nameVn: 'Nền tảng & chuyên sâu SASS/SCSS thực tế qua dự án',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0005',
    nameEng: 'Programming thinking & background',
    nameVn: 'Tư duy lập trình & nền tảng',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0006',
    nameEng: 'Arrays, advanced basic data, fundamental algorithms',
    nameVn: 'Mảng, CTDL căn bản chuyên sâu, thuật toán nền tảng',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0007',
    nameEng: 'Deep foundational object-oriented programming',
    nameVn: 'Lập trình hướng đối tượng nền tảng chuyên sâu',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0008',
    nameEng:
      'Full range of foundational and in-depth Javascript, JS DOM & JS OOP',
    nameVn: 'Toàn tập Javascript, JS DOM & JS OOP nền tảng và chuyên sâu',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0009',
    nameEng: 'Javascript ES6 foundation and in-depth',
    nameVn: 'Javascript ES6 nền tảng và chuyên sâu',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0010',
    nameEng: 'Javascript Axios ES with Deep & Platform API',
    nameVn: 'Javascript Axios ES với API nền tảng & chuyên sâu',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0011',
    nameEng: 'Git, Team Management Tool, Scrum/Agile Model',
    nameVn: 'Git, công cụ quản lý nhóm, mô hình Scrum/Agile',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0012',
    nameEng: 'ReactJS platform through project demo',
    nameVn: 'ReactJS nền tảng qua demo dự án',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0013',
    nameEng: 'ReactJS is intensive on many components',
    nameVn: 'ReactJS chuyên sâu trên nhiều component',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0014',
    nameEng: 'React hook, redux toolkit - Online movie ticketing project',
    nameVn: 'React hook, redux toolkit - Dự án Đặt vé phim trực tuyến',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0015',
    nameEng: 'TypeScript - Organize a React Project Using TypeScript',
    nameVn: 'TypeScript - Tổ chức dự án React bằng TypeScript',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'CT_0016',
    nameEng: 'Summary of the full project at the end of the course',
    nameVn: 'Tổng hợp dự án full cuối khóa',
    courseId: 'C_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default courseTopic;
