import { District } from '@prisma/client';

const district: District[] = [
  // HCM
  {
    id: 'HC482',
    nameVn: 'Quận Thủ Đức',
    nameEng: 'District Thu Duc',
    code: 'HC482',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC485',
    nameVn: 'Huyện Bình Chánh',
    nameEng: 'District Binh Chanh',
    code: 'HC485',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC486',
    nameVn: 'Huyện Nhà Bè',
    nameEng: 'District Nha Be',
    code: 'HC486',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC478',
    nameVn: 'Quận Gò Vấp',
    nameEng: 'District Go Vap',
    code: 'HC478',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC487',
    nameVn: 'Huyện Cần Giờ',
    nameEng: 'District Can Gio',
    code: 'HC487',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC479',
    nameVn: 'Quận Tân Bình',
    nameEng: 'District Tan Binh',
    code: 'HC479',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC679',
    nameVn: 'Quận Bình Tân',
    nameEng: 'District Binh Tan',
    code: 'HC679',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC480',
    nameVn: 'Quận Bình Thạnh',
    nameEng: 'District Binh Thanh',
    code: 'HC480',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC483',
    nameVn: 'Huyện Củ Chi',
    nameEng: 'District Cu Chi',
    code: 'HC483',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC680',
    nameVn: 'Quận Tân Phú',
    nameEng: 'District Tan Phu',
    code: 'HC680',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC481',
    nameVn: 'Quận Phú Nhuận',
    nameEng: 'District Phu Nhuan',
    code: 'HC481',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC484',
    nameVn: 'Huyện Hóc Môn',
    nameEng: 'District Hoc Mon',
    code: 'HC484',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC466',
    nameVn: 'Quận 1',
    nameEng: 'District 1',
    code: 'HC466',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC467',
    nameVn: 'Quận 2',
    nameEng: 'District 2',
    code: 'HC467',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC468',
    nameVn: 'Quận 3',
    nameEng: 'District 3',
    code: 'HC468',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC469',
    nameVn: 'Quận 4',
    nameEng: 'District 4',
    code: 'HC469',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC470',
    nameVn: 'Quận 5',
    nameEng: 'District 5',
    code: 'HC470',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC471',
    nameVn: 'Quận 6',
    nameEng: 'District 6',
    code: 'HC471',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC472',
    nameVn: 'Quận 7',
    nameEng: 'District 7',
    code: 'HC472',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC473',
    nameVn: 'Quận 8',
    nameEng: 'District 8',
    code: 'HC473',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC474',
    nameVn: 'Quận 9',
    nameEng: 'District 9',
    code: 'HC474',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 'HC475',
    nameVn: 'Quận 10',
    nameEng: 'District 10',
    code: 'HC475',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC476',
    nameVn: 'Quận 11',
    nameEng: 'District 11',
    code: 'HC476',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HC477',
    nameVn: 'Quận 12',
    nameEng: 'District 12',
    code: 'HC477',
    cityCode: 'HC',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // HN
  {
    id: 'HI708',
    nameVn: 'Huyện Thanh Oai',
    nameEng: 'District Thanh Oai',
    code: 'HI708',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI12',
    nameVn: 'Huyện Từ Liêm',
    nameEng: 'District Tu Liem',
    code: 'HI12',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI7',
    nameVn: 'Quận Thanh Xuân',
    nameEng: 'District Thanh Xuan',
    code: 'HI7',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI703',
    nameVn: 'Huyện Mỹ Đức',
    nameEng: 'District My Duc',
    code: 'HI703',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI2',
    nameVn: 'Quận Ba Đình',
    nameEng: 'District Ba Dinh',
    code: 'HI2',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI698',
    nameVn: 'Thị xã Sơn Tây',
    nameEng: 'Son Tay Town',
    code: 'HI698',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI710',
    nameVn: 'Huyện Thường Tín',
    nameEng: 'District Thuong Tin',
    code: 'HI710',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI13',
    nameVn: 'Huyện Thanh Trì',
    nameEng: 'District Thanh Tri',
    code: 'HI13',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI8',
    nameVn: 'Quận Cầu Giấy',
    nameEng: 'District Cau Giay',
    code: 'HI8',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI704',
    nameVn: 'Huyện Phú Xuyên',
    nameEng: 'District Phu Xuyen',
    code: 'HI704',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI3',
    nameVn: 'Quận Tây Hồ',
    nameEng: 'District Tay Ho',
    code: 'HI3',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI699',
    nameVn: 'Huyện Ba Vì',
    nameEng: 'District Ba Vi',
    code: 'HI699',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI711',
    nameVn: 'Huyện Ứng Hòa',
    nameEng: 'District Ung Hoa',
    code: 'HI711',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI34',
    nameVn: 'Huyện Mê Linh',
    nameEng: 'District Me Linh',
    code: 'HI34',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI9',
    nameVn: 'Huyện Sóc Sơn',
    nameEng: 'District Soc Son',
    code: 'HI9',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI705',
    nameVn: 'Huyện Phúc Thọ',
    nameEng: 'District Phuc Tho',
    code: 'HI705',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI4',
    nameVn: 'Quận Hoàn Kiếm',
    nameEng: 'District Hoan Kiem',
    code: 'HI4',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI700',
    nameVn: 'Huyện Chương Mỹ',
    nameEng: 'District Chuong My',
    code: 'HI700',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI810',
    nameVn: 'Quận Bắc Từ Liêm',
    nameEng: 'District Bac Tu Liem',
    code: 'HI810',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI687',
    nameVn: 'Quận Hà Đông',
    nameEng: 'District Ha Dong',
    code: 'HI687',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI10',
    nameVn: 'Huyện Đông Anh',
    nameEng: 'District Dong Anh',
    code: 'HI10',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI706',
    nameVn: 'Huyện Quốc Oai',
    nameEng: 'District Quoc Oai',
    code: 'HI706',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI5',
    nameVn: 'Quận Hai Bà Trưng',
    nameEng: 'District Ha Ba Trung',
    code: 'HI5',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI701',
    nameVn: 'Huyện Đan Phượng',
    nameEng: 'District Dan Phuong',
    code: 'HI701',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI811',
    nameVn: 'Quận Nam Từ Liêm',
    nameEng: 'District Nam Tu Liem',
    code: 'HI811',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI688',
    nameVn: 'Quận Hoàng Mai',
    nameEng: 'District Hoang Mai',
    code: 'HI688',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI707',
    nameVn: 'Huyện Thạch Thất',
    nameEng: 'District Thach That',
    code: 'HI707',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI11',
    nameVn: 'Huyện Gia Lâm',
    nameEng: 'District Gia Lam',
    code: 'HI11',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI6',
    nameVn: 'Quận Đống Đa',
    nameEng: 'District Dong Da',
    code: 'HI6',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI702',
    nameVn: 'Huyện Hoài Đức',
    nameEng: 'District Hoai Duc',
    code: 'HI702',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'HI689',
    nameVn: 'Quận Long Biên',
    nameEng: 'District Long Bien',
    code: 'HI689',
    cityCode: 'HI',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default district;
