import { Tag } from '@prisma/client';

const tag: Tag[] = [
  {
    id: 'T_0001',
    nameEng: 'html',
    nameVn: 'html',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0002',
    nameEng: 'html5',
    nameVn: 'html5',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0003',
    nameEng: 'css',
    nameVn: 'css',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0004',
    nameEng: 'css3',
    nameVn: 'css3',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0005',
    nameEng: 'javascript',
    nameVn: 'javascript',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0006',
    nameEng: 'es6 js',
    nameVn: 'es6 js',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0007',
    nameEng: 'json',
    nameVn: 'json',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0008',
    nameEng: 'ajax',
    nameVn: 'ajax',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0009',
    nameEng: 'axios',
    nameVn: 'axios',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0010',
    nameEng: 'reactjs',
    nameVn: 'reactjs',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0011',
    nameEng: 'nextjs',
    nameVn: 'nextjs',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0012',
    nameEng: 'angular',
    nameVn: 'angular',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0013',
    nameEng: 'vue',
    nameVn: 'vue',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0014',
    nameEng: 'java',
    nameVn: 'java',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0015',
    nameEng: 'spring boot',
    nameVn: 'spring boot',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0016',
    nameEng: 'career orientation',
    nameVn: 'định hướng nghề nghiệp',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0017',
    nameEng: 'vocational skills',
    nameVn: 'kỹ năng nghề',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0018',
    nameEng: 'how to learn programming',
    nameVn: 'cách học lập trình',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0019',
    nameEng: 'project organization',
    nameVn: 'tổ chức dự án',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0020',
    nameEng: 'deploy',
    nameVn: 'triển khai',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0021',
    nameEng: 'ui/ux',
    nameVn: 'ui/ux',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0022',
    nameEng: 'git',
    nameVn: 'git',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0023',
    nameEng: 'github',
    nameVn: 'github',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0024',
    nameEng: 'redux',
    nameVn: 'redux',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'T_0025',
    nameEng: 'typescript',
    nameVn: 'typescript',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default tag;
