import { TaskToDo } from '@prisma/client';

const taskTodo: TaskToDo[] = [
  // PT_0001
  {
    id: 'TD_0001',
    contentEng: 'Interface for the Home page',
    contentVn: 'Giao diện cho trang Home',
    taskId: 'PT_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0002',
    contentEng: 'Interface for Registration/Login page',
    contentVn: 'Giao diện cho trang Đăng kí/Đăng nhập',
    taskId: 'PT_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0003',
    contentEng: 'Interface Room List, Room Details, Comments',
    contentVn: 'Giao diện Danh sách phòng, Chi tiết phòng, Bình luận',
    taskId: 'PT_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0004',
    contentEng: 'Booking interface',
    contentVn: 'Giao diện Đặt phòng',
    taskId: 'PT_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0005',
    contentEng:
      'Interface for the Personal Information page, Reservation History',
    contentVn: 'Giao diện cho trang Thông tin cá nhân, Lịch sử đặt phòng',
    taskId: 'PT_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0006',
    contentEng: 'Build Admin Dashboard interface to manage the system',
    contentVn: 'Xây dựng giao diện Admin Dashboard để quản lí hệ thống',
    taskId: 'PT_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0007',
    contentEng: 'Location, room, reservation management interface',
    contentVn: 'Giao diện quản lí Địa điểm, phòng, đặt phòng',
    taskId: 'PT_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0008',
    contentEng: 'User management interface',
    contentVn: 'Giao diện quản lí User',
    taskId: 'PT_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0009',
    contentEng: 'Web Host on Heroku, Vercel',
    contentVn: 'Host web trên Heroku, Vercel',
    taskId: 'PT_0001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // PT 0002
  {
    id: 'TD_0010',
    contentEng: 'Implement the function for retrieving and searching rooms',
    contentVn: 'Thực hiện chức năng cho lấy và tìm kiếm phòng',
    taskId: 'PT_0002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0011',
    contentEng: 'Login/Register for users, and categorize users',
    contentVn: 'Đăng nhập/Đăng kí cho người dùng, và phân loại người dùng',
    taskId: 'PT_0002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0012',
    contentEng:
      'Validate the registration/login form before working with the API',
    contentVn: 'Xác thực form đăng kí/đăng nhập trước khi thao tác với API',
    taskId: 'PT_0002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0013',
    contentEng:
      'Implement the function Edit personal information, view booking history',
    contentVn:
      'Thực hiện chức năng Sửa thông tin cá nhân, xem lịch sử đặt phòng',
    taskId: 'PT_0002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0014',
    contentEng: 'Implement the Reservation function',
    contentVn: 'Thực hiện chức năng Đặt phòng',
    taskId: 'PT_0002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0015',
    contentEng: 'Implement functions in CRUD for room and location management',
    contentVn: 'Thực hiện các chức năng trong CRUD cho quản lý phòng, địa điểm',
    taskId: 'PT_0002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0016',
    contentEng: 'Implement functions in CRUD for user management',
    contentVn: 'Thực hiện các chức năng trong CRUD cho quản lý người dùng',
    taskId: 'PT_0002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0017',
    contentEng: 'Implement functions in CRUD for reservation management',
    contentVn: 'Thực hiện các chức năng trong CRUD cho quản lý đặt phòng',
    taskId: 'PT_0002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // PT_0003
  {
    id: 'TD_0018',
    contentEng: 'Teamwork skill',
    contentVn: 'Kỹ năng làm việc nhóm',
    taskId: 'PT_0003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0019',
    contentEng: 'Task and time management',
    contentVn: 'Quản lý task và thời gian',
    taskId: 'PT_0003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0020',
    contentEng: 'Manage source code with github',
    contentVn: 'Quản lý source code bằng github',
    taskId: 'PT_0003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0021',
    contentEng: 'Project presentation',
    contentVn: 'Trình bày đồ án',
    taskId: 'PT_0003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0022',
    contentEng: 'CV writing and interviewing skills',
    contentVn: 'Kỹ năng viết CV và phỏng vấn',
    taskId: 'PT_0003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // PT_0004
  {
    id: 'TD_0023',
    contentEng: 'Interface for Dashboard page displaying projects',
    contentVn: 'Giao diện cho trang Dashboard hiển thị các dự án',
    taskId: 'PT_0004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0024',
    contentEng: 'Interface for Registration/Login page',
    contentVn: 'Giao diện cho trang Đăng kí/Đăng nhập',
    taskId: 'PT_0004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0025',
    contentEng:
      'Task management interface: create task, assign task, delete task',
    contentVn: 'Giao diện quản lý task: tạo task, giao task, xoá task',
    taskId: 'PT_0004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0026',
    contentEng: 'Interface to view task details, view comments',
    contentVn: 'Giao diện xem thông tin chi tiết task, xem bình luận',
    taskId: 'PT_0004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0027',
    contentEng:
      'Task editing interface (status, deadline, description...), comment editing',
    contentVn:
      'Giao diện chỉnh sửa task (trạng thái, deadline, mô tả…), chỉnh sửa bình luận',
    taskId: 'PT_0004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0028',
    contentEng: 'User management interface',
    contentVn: 'Giao diện quản lý người dùng',
    taskId: 'PT_0004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0029',
    contentEng: 'Web Host on Heroku, Vercel',
    contentVn: 'Host web trên Heroku, Vercel',
    taskId: 'PT_0004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // PT_0005
  {
    id: 'TD_0030',
    contentEng: 'Implement functions for filtering and searching tasks',
    contentVn: 'Thực hiện chức năng cho lọc và tìm kiếm task',
    taskId: 'PT_0005',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0031',
    contentEng:
      'Validate the registration/login form before working with the API',
    contentVn: 'Xác thực form đăng kí/đăng nhập trước khi thao tác với API',
    taskId: 'PT_0005',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0032',
    contentEng:
      'Implement User Registration/Login function, and user classification',
    contentVn:
      'Thực hiện chức năng Đăng kí/Đăng nhập cho người dùng, và phân loại người dùng',
    taskId: 'PT_0005',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0033',
    contentEng: 'Implement the function of Editing personal information',
    contentVn: 'Thực hiện chức năng Sửa thông tin cá nhân',
    taskId: 'PT_0005',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0034',
    contentEng: 'Implement CRUD functions for task management',
    contentVn: 'Thực hiện các chức năng trong CRUD cho quản lý task',
    taskId: 'PT_0005',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0035',
    contentEng: 'Implement functions in CRUD for user management',
    contentVn: 'Thực hiện các chức năng trong CRUD cho quản lý người dùng',
    taskId: 'PT_0005',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0036',
    contentEng: 'Implement CRUD functions for project management',
    contentVn: 'Thực hiện các chức năng trong CRUD cho quản lý dự án',
    taskId: 'PT_0005',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // PT_0006
  {
    id: 'TD_0037',
    contentEng: 'Teamwork skill',
    contentVn: 'Kỹ năng làm việc nhóm',
    taskId: 'PT_0006',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0038',
    contentEng: 'Task and time management',
    contentVn: 'Quản lý task và thời gian',
    taskId: 'PT_0006',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0039',
    contentEng: 'Manage source code with github',
    contentVn: 'Quản lý source code bằng github',
    taskId: 'PT_0006',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0040',
    contentEng: 'Project presentation',
    contentVn: 'Trình bày đồ án',
    taskId: 'PT_0006',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0041',
    contentEng: 'CV writing and interviewing skills',
    contentVn: 'Kỹ năng viết CV và phỏng vấn',
    taskId: 'PT_0006',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // PT_0007
  {
    id: 'TD_0042',
    contentEng: 'Interface for the Home page',
    contentVn: 'Giao diện cho trang Home',
    taskId: 'PT_0007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0043',
    contentEng: 'Interface for the Registration page',
    contentVn: 'Giao diện cho trang Đăng kí',
    taskId: 'PT_0007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0044',
    contentEng: 'Interface for Login page',
    contentVn: 'Giao diện cho trang Đăng nhập',
    taskId: 'PT_0007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0045',
    contentEng: 'Task List interface',
    contentVn: 'Giao diện Danh sách các công việc',
    taskId: 'PT_0007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0046',
    contentEng: 'Job Directory interface',
    contentVn: 'Giao diện Danh mục việc làm',
    taskId: 'PT_0007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0047',
    contentEng: 'HR Hire Interface',
    contentVn: 'Giao diện Thuê nhân sự',
    taskId: 'PT_0007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0048',
    contentEng: 'Interface for Personnel Details page',
    contentVn: 'Giao diện cho trang Thông tin chi tiết nhân sự',
    taskId: 'PT_0007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0049',
    contentEng: 'Personal information page interface',
    contentVn: 'Giao diện trang Thông tin cá nhân',
    taskId: 'PT_0007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0050',
    contentEng: 'Build Admin Dashboard interface to manage the system',
    contentVn: 'Xây dựng giao diện Admin Dashboard để quản lí hệ thống',
    taskId: 'PT_0007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0051',
    contentEng: 'User management interface',
    contentVn: 'Giao diện quản lí User',
    taskId: 'PT_0007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0052',
    contentEng: 'Web Host on Heroku, Vercel',
    contentVn: 'Host web trên Heroku, Vercel',
    taskId: 'PT_0007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  //  P_0008
  {
    id: 'TD_0053',
    contentEng:
      'Implement the function for getting and searching for jobs, job types',
    contentVn:
      'Thực hiện chức năng cho lấy và tìm kiếm công việc, loại công việc',
    taskId: 'PT_0008',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0054',
    contentEng: 'Login/Register for users, and categorize users',
    contentVn: 'Đăng nhập/Đăng kí cho người dùng, và phân loại người dùng',
    taskId: 'PT_0008',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0055',
    contentEng:
      'Validate the registration/login form before working with the API',
    contentVn: 'Xác thực form đăng kí/đăng nhập trước khi thao tác với API',
    taskId: 'PT_0008',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0056',
    contentEng: 'Implement the function of Editing personal information',
    contentVn: 'Thực hiện chức năng Sửa thông tin cá nhân',
    taskId: 'PT_0008',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0057',
    contentEng: 'Implement the function of Hiring personnel',
    contentVn: 'Thực hiện chức năng Thuê nhân sự',
    taskId: 'PT_0008',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0058',
    contentEng: 'Implement functions in CRUD for job management, job type',
    contentVn:
      'Thực hiện các chức năng trong CRUD cho quản lý công việc, loại công việc',
    taskId: 'PT_0008',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0059',
    contentEng: 'Implement functions in CRUD for user management',
    contentVn: 'Thực hiện các chức năng trong CRUD cho quản lý người dùng',
    taskId: 'PT_0008',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  //  PT_0009
  {
    id: 'TD_0060',
    contentEng: 'Teamwork skill',
    contentVn: 'Kỹ năng làm việc nhóm',
    taskId: 'PT_0009',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0061',
    contentEng: 'Task and time management',
    contentVn: 'Quản lý task và thời gian',
    taskId: 'PT_0009',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0062',
    contentEng: 'Manage source code with github',
    contentVn: 'Quản lý source code bằng github',
    taskId: 'PT_0009',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0063',
    contentEng: 'Project presentation',
    contentVn: 'Trình bày đồ án',
    taskId: 'PT_0009',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0064',
    contentEng: 'CV writing and interviewing skills',
    contentVn: 'Kỹ năng viết CV và phỏng vấn',
    taskId: 'PT_0009',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // PT 0010
  {
    id: 'TD_0065',
    contentEng: 'Login/Register for users, and classify users',
    contentVn: 'Đăng nhập/Đăng kí cho người dùng, và phân chia loại người dùng',
    taskId: 'PT_0010',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0066',
    contentEng: 'Interface for the homepage',
    contentVn: 'Giao diện cho trang chủ',
    taskId: 'PT_0010',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0067',
    contentEng: 'Interface for Registration/Login page',
    contentVn: 'Giao diện cho trang Đăng kí/Đăng nhập',
    taskId: 'PT_0010',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0068',
    contentEng: 'Interface for details page',
    contentVn: 'Giao diện cho trang chi tiết',
    taskId: 'PT_0010',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0069',
    contentEng: 'Interface for user information page',
    contentVn: 'Giao diện cho trang thông tin người dùng',
    taskId: 'PT_0010',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0070',
    contentEng: 'Build Admin Dashboard interface to manage the system',
    contentVn: 'Xây dựng giao diện Admin Dashboard để quản lí hệ thống',
    taskId: 'PT_0010',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0071',
    contentEng: 'Course management interface',
    contentVn: 'Giao diện quản lí khóa học',
    taskId: 'PT_0010',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0072',
    contentEng: 'User management interface',
    contentVn: 'Giao diện quản lí người dùng',
    taskId: 'PT_0010',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0073',
    contentEng: 'Course enrollment management interface',
    contentVn: 'Giao diện quản lí ghi danh khóa học',
    taskId: 'PT_0010',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0074',
    contentEng: 'Web Host on Heroku, Vercel',
    contentVn: 'Host web trên Heroku, Vercel',
    taskId: 'PT_0010',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // PT_0011
  {
    id: 'TD_0075',
    contentEng:
      'Implement the function for retrieving and searching for courses',
    contentVn: 'Thực hiện chức năng cho lấy và tìm kiếm khóa học',
    taskId: 'PT_0011',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0076',
    contentEng:
      'Validate the registration/login form before working with the API',
    contentVn: 'Xác thực form đăng kí/đăng nhập trước khi thao tác với API',
    taskId: 'PT_0011',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0077',
    contentEng: 'Implement the Register/Login function',
    contentVn: 'Thực hiện chức năng Đăng kí/Đăng nhập',
    taskId: 'PT_0011',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0078',
    contentEng: 'Implement the function of Editing personal information',
    contentVn: 'Thực hiện chức năng Sửa thông tin cá nhân',
    taskId: 'PT_0011',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0079',
    contentEng:
      'Implement the function to register and unsubscribe from the course',
    contentVn: 'Thực hiện chức năng đăng ký và hủy đăng ký khóa học',
    taskId: 'PT_0011',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0080',
    contentEng: 'Implement functions in CRUD for course management',
    contentVn: 'Thực hiện các chức năng trong CRUD cho quản lý khóa học',
    taskId: 'PT_0011',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0081',
    contentEng: 'Implement functions in CRUD for user management',
    contentVn: 'Thực hiện các chức năng trong CRUD cho quản lý người dùng',
    taskId: 'PT_0011',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0082',
    contentEng:
      'Basic statistics of data and displayed as pie chart, bar chart',
    contentVn:
      'Thống kê cơ bản các dữ liệu và hiện dưới dạng pie chart, bar chart',
    taskId: 'PT_0011',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // PT_0012
  {
    id: 'TD_0083',
    contentEng: 'Teamwork skill',
    contentVn: 'Kỹ năng làm việc nhóm',
    taskId: 'PT_0012',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0084',
    contentEng: 'Task and time management',
    contentVn: 'Quản lý task và thời gian',
    taskId: 'PT_0012',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0085',
    contentEng: 'Manage source code with github',
    contentVn: 'Quản lý source code bằng github',
    taskId: 'PT_0012',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0086',
    contentEng: 'Project presentation',
    contentVn: 'Trình bày đồ án',
    taskId: 'PT_0012',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TD_0087',
    contentEng: 'CV writing and interviewing skills',
    contentVn: 'Kỹ năng viết CV và phỏng vấn',
    taskId: 'PT_0012',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default taskTodo;
